language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      dist: bionic
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
install: pip install -r requirements.txt  # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  - python3 src/test/AutoDDMTestWeather.py || python src/test/AutoDDMTestWeather.py
  - python3 src/test/DDMTestWeather.py || python src/test/DDMTestWeather.py
  - python3 src/test/AutoTestElectricityData.py || python src/test/AutoTestElectricityData.py
  - python3 src/test/DDMTestElectricityData.py || python src/test/DDMTestElectricityData.py
  - python3 src/test/testAutoDDMnoise.py || python src/test/testAutoDDMnoise.py
  - python3 src/test/testDDMnoise.py || python src/test/testDDMnoise.py
